// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/features/auth (interfaces: AuthService)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_auth_service.go -package=mocks care-cordination/features/auth AuthService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "care-cordination/features/auth"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// DisableMFA mocks base method.
func (m *MockAuthService) DisableMFA(ctx context.Context, req *auth.DisableMFARequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableMFA", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableMFA indicates an expected call of DisableMFA.
func (mr *MockAuthServiceMockRecorder) DisableMFA(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableMFA", reflect.TypeOf((*MockAuthService)(nil).DisableMFA), ctx, req)
}

// EnableMFA mocks base method.
func (m *MockAuthService) EnableMFA(ctx context.Context, req *auth.EnableMFARequest) (*auth.EnableMFAResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableMFA", ctx, req)
	ret0, _ := ret[0].(*auth.EnableMFAResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableMFA indicates an expected call of EnableMFA.
func (mr *MockAuthServiceMockRecorder) EnableMFA(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableMFA", reflect.TypeOf((*MockAuthService)(nil).EnableMFA), ctx, req)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, req *auth.LoginRequest, userAgent, ipAddress string) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req, userAgent, ipAddress)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, req, userAgent, ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, req, userAgent, ipAddress)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, req *auth.LogoutRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, req)
}

// RefreshTokens mocks base method.
func (m *MockAuthService) RefreshTokens(ctx context.Context, req *auth.RefreshTokensRequest, userAgent, ipAddress string) (*auth.RefreshTokensResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, req, userAgent, ipAddress)
	ret0, _ := ret[0].(*auth.RefreshTokensResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAuthServiceMockRecorder) RefreshTokens(ctx, req, userAgent, ipAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAuthService)(nil).RefreshTokens), ctx, req, userAgent, ipAddress)
}

// ResetPassword mocks base method.
func (m *MockAuthService) ResetPassword(ctx context.Context, req *auth.ResetPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthServiceMockRecorder) ResetPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthService)(nil).ResetPassword), ctx, req)
}

// SetupMFA mocks base method.
func (m *MockAuthService) SetupMFA(ctx context.Context) (*auth.SetupMFAResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupMFA", ctx)
	ret0, _ := ret[0].(*auth.SetupMFAResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupMFA indicates an expected call of SetupMFA.
func (mr *MockAuthServiceMockRecorder) SetupMFA(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupMFA", reflect.TypeOf((*MockAuthService)(nil).SetupMFA), ctx)
}

// VerifyMFA mocks base method.
func (m *MockAuthService) VerifyMFA(ctx context.Context, req *auth.VerifyMFARequest, preAuthToken string) (*auth.VerifyMFAResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMFA", ctx, req, preAuthToken)
	ret0, _ := ret[0].(*auth.VerifyMFAResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyMFA indicates an expected call of VerifyMFA.
func (mr *MockAuthServiceMockRecorder) VerifyMFA(ctx, req, preAuthToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMFA", reflect.TypeOf((*MockAuthService)(nil).VerifyMFA), ctx, req, preAuthToken)
}
