// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/features/calendar (interfaces: CalendarService)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_calendar_service.go -package=mocks care-cordination/features/calendar CalendarService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	calendar "care-cordination/features/calendar"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCalendarService is a mock of CalendarService interface.
type MockCalendarService struct {
	ctrl     *gomock.Controller
	recorder *MockCalendarServiceMockRecorder
	isgomock struct{}
}

// MockCalendarServiceMockRecorder is the mock recorder for MockCalendarService.
type MockCalendarServiceMockRecorder struct {
	mock *MockCalendarService
}

// NewMockCalendarService creates a new mock instance.
func NewMockCalendarService(ctrl *gomock.Controller) *MockCalendarService {
	mock := &MockCalendarService{ctrl: ctrl}
	mock.recorder = &MockCalendarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalendarService) EXPECT() *MockCalendarServiceMockRecorder {
	return m.recorder
}

// CreateAppointment mocks base method.
func (m *MockCalendarService) CreateAppointment(ctx context.Context, organizerID string, req calendar.CreateAppointmentRequest) (*calendar.AppointmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", ctx, organizerID, req)
	ret0, _ := ret[0].(*calendar.AppointmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockCalendarServiceMockRecorder) CreateAppointment(ctx, organizerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockCalendarService)(nil).CreateAppointment), ctx, organizerID, req)
}

// CreateReminder mocks base method.
func (m *MockCalendarService) CreateReminder(ctx context.Context, userID string, req calendar.CreateReminderRequest) (*calendar.ReminderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReminder", ctx, userID, req)
	ret0, _ := ret[0].(*calendar.ReminderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReminder indicates an expected call of CreateReminder.
func (mr *MockCalendarServiceMockRecorder) CreateReminder(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReminder", reflect.TypeOf((*MockCalendarService)(nil).CreateReminder), ctx, userID, req)
}

// DeleteAppointment mocks base method.
func (m *MockCalendarService) DeleteAppointment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAppointment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAppointment indicates an expected call of DeleteAppointment.
func (mr *MockCalendarServiceMockRecorder) DeleteAppointment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAppointment", reflect.TypeOf((*MockCalendarService)(nil).DeleteAppointment), ctx, id)
}

// DeleteReminder mocks base method.
func (m *MockCalendarService) DeleteReminder(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReminder", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReminder indicates an expected call of DeleteReminder.
func (mr *MockCalendarServiceMockRecorder) DeleteReminder(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReminder", reflect.TypeOf((*MockCalendarService)(nil).DeleteReminder), ctx, id)
}

// GetAppointment mocks base method.
func (m *MockCalendarService) GetAppointment(ctx context.Context, id string) (*calendar.AppointmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointment", ctx, id)
	ret0, _ := ret[0].(*calendar.AppointmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointment indicates an expected call of GetAppointment.
func (mr *MockCalendarServiceMockRecorder) GetAppointment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointment", reflect.TypeOf((*MockCalendarService)(nil).GetAppointment), ctx, id)
}

// GetCalendarView mocks base method.
func (m *MockCalendarService) GetCalendarView(ctx context.Context, userID string, startTime, endTime time.Time) ([]calendar.CalendarEventDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCalendarView", ctx, userID, startTime, endTime)
	ret0, _ := ret[0].([]calendar.CalendarEventDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCalendarView indicates an expected call of GetCalendarView.
func (mr *MockCalendarServiceMockRecorder) GetCalendarView(ctx, userID, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCalendarView", reflect.TypeOf((*MockCalendarService)(nil).GetCalendarView), ctx, userID, startTime, endTime)
}

// GetReminder mocks base method.
func (m *MockCalendarService) GetReminder(ctx context.Context, id string) (*calendar.ReminderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReminder", ctx, id)
	ret0, _ := ret[0].(*calendar.ReminderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReminder indicates an expected call of GetReminder.
func (mr *MockCalendarServiceMockRecorder) GetReminder(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReminder", reflect.TypeOf((*MockCalendarService)(nil).GetReminder), ctx, id)
}

// ListAppointments mocks base method.
func (m *MockCalendarService) ListAppointments(ctx context.Context, userID string) ([]calendar.AppointmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAppointments", ctx, userID)
	ret0, _ := ret[0].([]calendar.AppointmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAppointments indicates an expected call of ListAppointments.
func (mr *MockCalendarServiceMockRecorder) ListAppointments(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAppointments", reflect.TypeOf((*MockCalendarService)(nil).ListAppointments), ctx, userID)
}

// ListReminders mocks base method.
func (m *MockCalendarService) ListReminders(ctx context.Context, userID string) ([]calendar.ReminderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReminders", ctx, userID)
	ret0, _ := ret[0].([]calendar.ReminderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReminders indicates an expected call of ListReminders.
func (mr *MockCalendarServiceMockRecorder) ListReminders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReminders", reflect.TypeOf((*MockCalendarService)(nil).ListReminders), ctx, userID)
}

// UpdateAppointment mocks base method.
func (m *MockCalendarService) UpdateAppointment(ctx context.Context, id string, req calendar.UpdateAppointmentRequest) (*calendar.AppointmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppointment", ctx, id, req)
	ret0, _ := ret[0].(*calendar.AppointmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAppointment indicates an expected call of UpdateAppointment.
func (mr *MockCalendarServiceMockRecorder) UpdateAppointment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppointment", reflect.TypeOf((*MockCalendarService)(nil).UpdateAppointment), ctx, id, req)
}

// UpdateReminder mocks base method.
func (m *MockCalendarService) UpdateReminder(ctx context.Context, id string, completed bool) (*calendar.ReminderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReminder", ctx, id, completed)
	ret0, _ := ret[0].(*calendar.ReminderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReminder indicates an expected call of UpdateReminder.
func (mr *MockCalendarServiceMockRecorder) UpdateReminder(ctx, id, completed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReminder", reflect.TypeOf((*MockCalendarService)(nil).UpdateReminder), ctx, id, completed)
}
