// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/features/dashboard (interfaces: DashboardService)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_dashboard_service.go -package=mocks care-cordination/features/dashboard DashboardService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dashboard "care-cordination/features/dashboard"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDashboardService is a mock of DashboardService interface.
type MockDashboardService struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardServiceMockRecorder
	isgomock struct{}
}

// MockDashboardServiceMockRecorder is the mock recorder for MockDashboardService.
type MockDashboardServiceMockRecorder struct {
	mock *MockDashboardService
}

// NewMockDashboardService creates a new mock instance.
func NewMockDashboardService(ctrl *gomock.Controller) *MockDashboardService {
	mock := &MockDashboardService{ctrl: ctrl}
	mock.recorder = &MockDashboardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardService) EXPECT() *MockDashboardServiceMockRecorder {
	return m.recorder
}

// GetCareTypeDistribution mocks base method.
func (m *MockDashboardService) GetCareTypeDistribution(ctx context.Context) (*dashboard.CareTypeDistributionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCareTypeDistribution", ctx)
	ret0, _ := ret[0].(*dashboard.CareTypeDistributionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCareTypeDistribution indicates an expected call of GetCareTypeDistribution.
func (mr *MockDashboardServiceMockRecorder) GetCareTypeDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCareTypeDistribution", reflect.TypeOf((*MockDashboardService)(nil).GetCareTypeDistribution), ctx)
}

// GetCoordinatorClients mocks base method.
func (m *MockDashboardService) GetCoordinatorClients(ctx context.Context, employeeID string) (*dashboard.CoordinatorClientsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorClients", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorClientsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorClients indicates an expected call of GetCoordinatorClients.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorClients(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorClients", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorClients), ctx, employeeID)
}

// GetCoordinatorGoalsProgress mocks base method.
func (m *MockDashboardService) GetCoordinatorGoalsProgress(ctx context.Context, employeeID string) (*dashboard.CoordinatorGoalsProgressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorGoalsProgress", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorGoalsProgressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorGoalsProgress indicates an expected call of GetCoordinatorGoalsProgress.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorGoalsProgress(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorGoalsProgress", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorGoalsProgress), ctx, employeeID)
}

// GetCoordinatorIncidents mocks base method.
func (m *MockDashboardService) GetCoordinatorIncidents(ctx context.Context, employeeID string) (*dashboard.CoordinatorIncidentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorIncidents", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorIncidentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorIncidents indicates an expected call of GetCoordinatorIncidents.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorIncidents(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorIncidents", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorIncidents), ctx, employeeID)
}

// GetCoordinatorReminders mocks base method.
func (m *MockDashboardService) GetCoordinatorReminders(ctx context.Context, employeeID string) (*dashboard.CoordinatorRemindersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorReminders", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorRemindersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorReminders indicates an expected call of GetCoordinatorReminders.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorReminders(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorReminders", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorReminders), ctx, employeeID)
}

// GetCoordinatorStats mocks base method.
func (m *MockDashboardService) GetCoordinatorStats(ctx context.Context, employeeID string) (*dashboard.CoordinatorStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorStats", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorStats indicates an expected call of GetCoordinatorStats.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorStats(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorStats", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorStats), ctx, employeeID)
}

// GetCoordinatorTodaySchedule mocks base method.
func (m *MockDashboardService) GetCoordinatorTodaySchedule(ctx context.Context, employeeID string) (*dashboard.CoordinatorTodayScheduleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorTodaySchedule", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorTodayScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorTodaySchedule indicates an expected call of GetCoordinatorTodaySchedule.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorTodaySchedule(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorTodaySchedule", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorTodaySchedule), ctx, employeeID)
}

// GetCoordinatorUrgentAlerts mocks base method.
func (m *MockDashboardService) GetCoordinatorUrgentAlerts(ctx context.Context, employeeID string) (*dashboard.CoordinatorUrgentAlertsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorUrgentAlerts", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorUrgentAlertsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorUrgentAlerts indicates an expected call of GetCoordinatorUrgentAlerts.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorUrgentAlerts(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorUrgentAlerts", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorUrgentAlerts), ctx, employeeID)
}

// GetCriticalAlerts mocks base method.
func (m *MockDashboardService) GetCriticalAlerts(ctx context.Context) (*dashboard.CriticalAlertsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCriticalAlerts", ctx)
	ret0, _ := ret[0].(*dashboard.CriticalAlertsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCriticalAlerts indicates an expected call of GetCriticalAlerts.
func (mr *MockDashboardServiceMockRecorder) GetCriticalAlerts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCriticalAlerts", reflect.TypeOf((*MockDashboardService)(nil).GetCriticalAlerts), ctx)
}

// GetDischargeStats mocks base method.
func (m *MockDashboardService) GetDischargeStats(ctx context.Context) (*dashboard.DischargeStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDischargeStats", ctx)
	ret0, _ := ret[0].(*dashboard.DischargeStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDischargeStats indicates an expected call of GetDischargeStats.
func (mr *MockDashboardServiceMockRecorder) GetDischargeStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDischargeStats", reflect.TypeOf((*MockDashboardService)(nil).GetDischargeStats), ctx)
}

// GetEvaluationStats mocks base method.
func (m *MockDashboardService) GetEvaluationStats(ctx context.Context) (*dashboard.EvaluationStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluationStats", ctx)
	ret0, _ := ret[0].(*dashboard.EvaluationStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluationStats indicates an expected call of GetEvaluationStats.
func (mr *MockDashboardServiceMockRecorder) GetEvaluationStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluationStats", reflect.TypeOf((*MockDashboardService)(nil).GetEvaluationStats), ctx)
}

// GetLocationCapacity mocks base method.
func (m *MockDashboardService) GetLocationCapacity(ctx context.Context, req *dashboard.LocationCapacityRequest) (*dashboard.LocationCapacityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationCapacity", ctx, req)
	ret0, _ := ret[0].(*dashboard.LocationCapacityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationCapacity indicates an expected call of GetLocationCapacity.
func (mr *MockDashboardServiceMockRecorder) GetLocationCapacity(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationCapacity", reflect.TypeOf((*MockDashboardService)(nil).GetLocationCapacity), ctx, req)
}

// GetOverviewStats mocks base method.
func (m *MockDashboardService) GetOverviewStats(ctx context.Context) (*dashboard.OverviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverviewStats", ctx)
	ret0, _ := ret[0].(*dashboard.OverviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverviewStats indicates an expected call of GetOverviewStats.
func (mr *MockDashboardServiceMockRecorder) GetOverviewStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverviewStats", reflect.TypeOf((*MockDashboardService)(nil).GetOverviewStats), ctx)
}

// GetPipelineStats mocks base method.
func (m *MockDashboardService) GetPipelineStats(ctx context.Context) (*dashboard.PipelineStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineStats", ctx)
	ret0, _ := ret[0].(*dashboard.PipelineStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineStats indicates an expected call of GetPipelineStats.
func (mr *MockDashboardServiceMockRecorder) GetPipelineStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineStats", reflect.TypeOf((*MockDashboardService)(nil).GetPipelineStats), ctx)
}

// GetTodayAppointments mocks base method.
func (m *MockDashboardService) GetTodayAppointments(ctx context.Context, employeeID string) (*dashboard.TodayAppointmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayAppointments", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.TodayAppointmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayAppointments indicates an expected call of GetTodayAppointments.
func (mr *MockDashboardServiceMockRecorder) GetTodayAppointments(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayAppointments", reflect.TypeOf((*MockDashboardService)(nil).GetTodayAppointments), ctx, employeeID)
}
