// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/features/employee (interfaces: EmployeeService)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_employee_service.go -package=mocks care-cordination/features/employee EmployeeService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	employee "care-cordination/features/employee"
	resp "care-cordination/lib/resp"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmployeeService is a mock of EmployeeService interface.
type MockEmployeeService struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeServiceMockRecorder
	isgomock struct{}
}

// MockEmployeeServiceMockRecorder is the mock recorder for MockEmployeeService.
type MockEmployeeServiceMockRecorder struct {
	mock *MockEmployeeService
}

// NewMockEmployeeService creates a new mock instance.
func NewMockEmployeeService(ctrl *gomock.Controller) *MockEmployeeService {
	mock := &MockEmployeeService{ctrl: ctrl}
	mock.recorder = &MockEmployeeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeService) EXPECT() *MockEmployeeServiceMockRecorder {
	return m.recorder
}

// CreateEmployee mocks base method.
func (m *MockEmployeeService) CreateEmployee(ctx context.Context, req *employee.CreateEmployeeRequest) (employee.CreateEmployeeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, req)
	ret0, _ := ret[0].(employee.CreateEmployeeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockEmployeeServiceMockRecorder) CreateEmployee(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockEmployeeService)(nil).CreateEmployee), ctx, req)
}

// DeleteEmployee mocks base method.
func (m *MockEmployeeService) DeleteEmployee(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockEmployeeServiceMockRecorder) DeleteEmployee(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockEmployeeService)(nil).DeleteEmployee), ctx, id)
}

// GetEmployeeByID mocks base method.
func (m *MockEmployeeService) GetEmployeeByID(ctx context.Context, id string) (*employee.GetEmployeeByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByID", ctx, id)
	ret0, _ := ret[0].(*employee.GetEmployeeByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByID indicates an expected call of GetEmployeeByID.
func (mr *MockEmployeeServiceMockRecorder) GetEmployeeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByID", reflect.TypeOf((*MockEmployeeService)(nil).GetEmployeeByID), ctx, id)
}

// GetMyProfile mocks base method.
func (m *MockEmployeeService) GetMyProfile(ctx context.Context) (*employee.GetMyProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyProfile", ctx)
	ret0, _ := ret[0].(*employee.GetMyProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyProfile indicates an expected call of GetMyProfile.
func (mr *MockEmployeeServiceMockRecorder) GetMyProfile(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyProfile", reflect.TypeOf((*MockEmployeeService)(nil).GetMyProfile), ctx)
}

// ListEmployees mocks base method.
func (m *MockEmployeeService) ListEmployees(ctx context.Context, req *employee.ListEmployeesRequest) (*resp.PaginationResponse[employee.ListEmployeesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", ctx, req)
	ret0, _ := ret[0].(*resp.PaginationResponse[employee.ListEmployeesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockEmployeeServiceMockRecorder) ListEmployees(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockEmployeeService)(nil).ListEmployees), ctx, req)
}

// UpdateEmployee mocks base method.
func (m *MockEmployeeService) UpdateEmployee(ctx context.Context, id string, req *employee.UpdateEmployeeRequest) (*employee.UpdateEmployeeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", ctx, id, req)
	ret0, _ := ret[0].(*employee.UpdateEmployeeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockEmployeeServiceMockRecorder) UpdateEmployee(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockEmployeeService)(nil).UpdateEmployee), ctx, id, req)
}
