// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/features/dashboard (interfaces: DashboardService)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_dashboard_service.go -package=mocks care-cordination/features/dashboard DashboardService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dashboard "care-cordination/features/dashboard"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDashboardService is a mock of DashboardService interface.
type MockDashboardService struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardServiceMockRecorder
	isgomock struct{}
}

// MockDashboardServiceMockRecorder is the mock recorder for MockDashboardService.
type MockDashboardServiceMockRecorder struct {
	mock *MockDashboardService
}

// NewMockDashboardService creates a new mock instance.
func NewMockDashboardService(ctrl *gomock.Controller) *MockDashboardService {
	mock := &MockDashboardService{ctrl: ctrl}
	mock.recorder = &MockDashboardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardService) EXPECT() *MockDashboardServiceMockRecorder {
	return m.recorder
}

// GetCareTypeDistribution mocks base method.
func (m *MockDashboardService) GetCareTypeDistribution(ctx context.Context) (*dashboard.CareTypeDistributionDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCareTypeDistribution", ctx)
	ret0, _ := ret[0].(*dashboard.CareTypeDistributionDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCareTypeDistribution indicates an expected call of GetCareTypeDistribution.
func (mr *MockDashboardServiceMockRecorder) GetCareTypeDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCareTypeDistribution", reflect.TypeOf((*MockDashboardService)(nil).GetCareTypeDistribution), ctx)
}

// GetCoordinatorTodaySchedule mocks base method.
func (m *MockDashboardService) GetCoordinatorTodaySchedule(ctx context.Context, employeeID string) (*dashboard.CoordinatorTodayScheduleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorTodaySchedule", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorTodayScheduleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorTodaySchedule indicates an expected call of GetCoordinatorTodaySchedule.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorTodaySchedule(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorTodaySchedule", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorTodaySchedule), ctx, employeeID)
}

// GetCoordinatorUrgentAlerts mocks base method.
func (m *MockDashboardService) GetCoordinatorUrgentAlerts(ctx context.Context, employeeID string) (*dashboard.CoordinatorUrgentAlertsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoordinatorUrgentAlerts", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.CoordinatorUrgentAlertsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoordinatorUrgentAlerts indicates an expected call of GetCoordinatorUrgentAlerts.
func (mr *MockDashboardServiceMockRecorder) GetCoordinatorUrgentAlerts(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoordinatorUrgentAlerts", reflect.TypeOf((*MockDashboardService)(nil).GetCoordinatorUrgentAlerts), ctx, employeeID)
}

// GetCriticalAlerts mocks base method.
func (m *MockDashboardService) GetCriticalAlerts(ctx context.Context) (*dashboard.CriticalAlertsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCriticalAlerts", ctx)
	ret0, _ := ret[0].(*dashboard.CriticalAlertsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCriticalAlerts indicates an expected call of GetCriticalAlerts.
func (mr *MockDashboardServiceMockRecorder) GetCriticalAlerts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCriticalAlerts", reflect.TypeOf((*MockDashboardService)(nil).GetCriticalAlerts), ctx)
}

// GetDischargeStats mocks base method.
func (m *MockDashboardService) GetDischargeStats(ctx context.Context) (*dashboard.DischargeStatsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDischargeStats", ctx)
	ret0, _ := ret[0].(*dashboard.DischargeStatsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDischargeStats indicates an expected call of GetDischargeStats.
func (mr *MockDashboardServiceMockRecorder) GetDischargeStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDischargeStats", reflect.TypeOf((*MockDashboardService)(nil).GetDischargeStats), ctx)
}

// GetEvaluationStats mocks base method.
func (m *MockDashboardService) GetEvaluationStats(ctx context.Context) (*dashboard.EvaluationStatsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluationStats", ctx)
	ret0, _ := ret[0].(*dashboard.EvaluationStatsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluationStats indicates an expected call of GetEvaluationStats.
func (mr *MockDashboardServiceMockRecorder) GetEvaluationStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluationStats", reflect.TypeOf((*MockDashboardService)(nil).GetEvaluationStats), ctx)
}

// GetLocationCapacity mocks base method.
func (m *MockDashboardService) GetLocationCapacity(ctx context.Context, req *dashboard.LocationCapacityRequest) (*dashboard.LocationCapacityDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationCapacity", ctx, req)
	ret0, _ := ret[0].(*dashboard.LocationCapacityDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationCapacity indicates an expected call of GetLocationCapacity.
func (mr *MockDashboardServiceMockRecorder) GetLocationCapacity(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationCapacity", reflect.TypeOf((*MockDashboardService)(nil).GetLocationCapacity), ctx, req)
}

// GetOverviewStats mocks base method.
func (m *MockDashboardService) GetOverviewStats(ctx context.Context) (*dashboard.OverviewDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverviewStats", ctx)
	ret0, _ := ret[0].(*dashboard.OverviewDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverviewStats indicates an expected call of GetOverviewStats.
func (mr *MockDashboardServiceMockRecorder) GetOverviewStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverviewStats", reflect.TypeOf((*MockDashboardService)(nil).GetOverviewStats), ctx)
}

// GetPipelineStats mocks base method.
func (m *MockDashboardService) GetPipelineStats(ctx context.Context) (*dashboard.PipelineStatsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineStats", ctx)
	ret0, _ := ret[0].(*dashboard.PipelineStatsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineStats indicates an expected call of GetPipelineStats.
func (mr *MockDashboardServiceMockRecorder) GetPipelineStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineStats", reflect.TypeOf((*MockDashboardService)(nil).GetPipelineStats), ctx)
}

// GetTodayAppointments mocks base method.
func (m *MockDashboardService) GetTodayAppointments(ctx context.Context, employeeID string) (*dashboard.TodayAppointmentsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodayAppointments", ctx, employeeID)
	ret0, _ := ret[0].(*dashboard.TodayAppointmentsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodayAppointments indicates an expected call of GetTodayAppointments.
func (mr *MockDashboardServiceMockRecorder) GetTodayAppointments(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodayAppointments", reflect.TypeOf((*MockDashboardService)(nil).GetTodayAppointments), ctx, employeeID)
}
