// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/features/client (interfaces: ClientService)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_client_service.go -package=mocks care-cordination/features/client ClientService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	client "care-cordination/features/client"
	resp "care-cordination/lib/resp"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientService is a mock of ClientService interface.
type MockClientService struct {
	ctrl     *gomock.Controller
	recorder *MockClientServiceMockRecorder
	isgomock struct{}
}

// MockClientServiceMockRecorder is the mock recorder for MockClientService.
type MockClientServiceMockRecorder struct {
	mock *MockClientService
}

// NewMockClientService creates a new mock instance.
func NewMockClientService(ctrl *gomock.Controller) *MockClientService {
	mock := &MockClientService{ctrl: ctrl}
	mock.recorder = &MockClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientService) EXPECT() *MockClientServiceMockRecorder {
	return m.recorder
}

// CompleteDischarge mocks base method.
func (m *MockClientService) CompleteDischarge(ctx context.Context, clientID string, req *client.CompleteDischargeRequest) (*client.CompleteDischargeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteDischarge", ctx, clientID, req)
	ret0, _ := ret[0].(*client.CompleteDischargeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteDischarge indicates an expected call of CompleteDischarge.
func (mr *MockClientServiceMockRecorder) CompleteDischarge(ctx, clientID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteDischarge", reflect.TypeOf((*MockClientService)(nil).CompleteDischarge), ctx, clientID, req)
}

// GetDischargeStats mocks base method.
func (m *MockClientService) GetDischargeStats(ctx context.Context) (*client.GetDischargeStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDischargeStats", ctx)
	ret0, _ := ret[0].(*client.GetDischargeStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDischargeStats indicates an expected call of GetDischargeStats.
func (mr *MockClientServiceMockRecorder) GetDischargeStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDischargeStats", reflect.TypeOf((*MockClientService)(nil).GetDischargeStats), ctx)
}

// GetInCareStats mocks base method.
func (m *MockClientService) GetInCareStats(ctx context.Context) (*client.GetInCareStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInCareStats", ctx)
	ret0, _ := ret[0].(*client.GetInCareStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInCareStats indicates an expected call of GetInCareStats.
func (mr *MockClientServiceMockRecorder) GetInCareStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInCareStats", reflect.TypeOf((*MockClientService)(nil).GetInCareStats), ctx)
}

// GetWaitlistStats mocks base method.
func (m *MockClientService) GetWaitlistStats(ctx context.Context) (*client.GetWaitlistStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistStats", ctx)
	ret0, _ := ret[0].(*client.GetWaitlistStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistStats indicates an expected call of GetWaitlistStats.
func (mr *MockClientServiceMockRecorder) GetWaitlistStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistStats", reflect.TypeOf((*MockClientService)(nil).GetWaitlistStats), ctx)
}

// ListClientGoals mocks base method.
func (m *MockClientService) ListClientGoals(ctx context.Context, clientID string) ([]client.ListClientGoalsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientGoals", ctx, clientID)
	ret0, _ := ret[0].([]client.ListClientGoalsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientGoals indicates an expected call of ListClientGoals.
func (mr *MockClientServiceMockRecorder) ListClientGoals(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientGoals", reflect.TypeOf((*MockClientService)(nil).ListClientGoals), ctx, clientID)
}

// ListDischargedClients mocks base method.
func (m *MockClientService) ListDischargedClients(ctx context.Context, req *client.ListDischargedClientsRequest) (*resp.PaginationResponse[client.ListDischargedClientsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDischargedClients", ctx, req)
	ret0, _ := ret[0].(*resp.PaginationResponse[client.ListDischargedClientsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDischargedClients indicates an expected call of ListDischargedClients.
func (mr *MockClientServiceMockRecorder) ListDischargedClients(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDischargedClients", reflect.TypeOf((*MockClientService)(nil).ListDischargedClients), ctx, req)
}

// ListInCareClients mocks base method.
func (m *MockClientService) ListInCareClients(ctx context.Context, req *client.ListInCareClientsRequest) (*resp.PaginationResponse[client.ListInCareClientsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInCareClients", ctx, req)
	ret0, _ := ret[0].(*resp.PaginationResponse[client.ListInCareClientsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInCareClients indicates an expected call of ListInCareClients.
func (mr *MockClientServiceMockRecorder) ListInCareClients(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInCareClients", reflect.TypeOf((*MockClientService)(nil).ListInCareClients), ctx, req)
}

// ListWaitingListClients mocks base method.
func (m *MockClientService) ListWaitingListClients(ctx context.Context, req *client.ListWaitingListClientsRequest) (*resp.PaginationResponse[client.ListWaitingListClientsResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWaitingListClients", ctx, req)
	ret0, _ := ret[0].(*resp.PaginationResponse[client.ListWaitingListClientsResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWaitingListClients indicates an expected call of ListWaitingListClients.
func (mr *MockClientServiceMockRecorder) ListWaitingListClients(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWaitingListClients", reflect.TypeOf((*MockClientService)(nil).ListWaitingListClients), ctx, req)
}

// MoveClientInCare mocks base method.
func (m *MockClientService) MoveClientInCare(ctx context.Context, clientID string, req *client.MoveClientInCareRequest) (*client.MoveClientInCareResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveClientInCare", ctx, clientID, req)
	ret0, _ := ret[0].(*client.MoveClientInCareResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveClientInCare indicates an expected call of MoveClientInCare.
func (mr *MockClientServiceMockRecorder) MoveClientInCare(ctx, clientID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveClientInCare", reflect.TypeOf((*MockClientService)(nil).MoveClientInCare), ctx, clientID, req)
}

// MoveClientToWaitingList mocks base method.
func (m *MockClientService) MoveClientToWaitingList(ctx context.Context, req *client.MoveClientToWaitingListRequest) (*client.MoveClientToWaitingListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveClientToWaitingList", ctx, req)
	ret0, _ := ret[0].(*client.MoveClientToWaitingListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveClientToWaitingList indicates an expected call of MoveClientToWaitingList.
func (mr *MockClientServiceMockRecorder) MoveClientToWaitingList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveClientToWaitingList", reflect.TypeOf((*MockClientService)(nil).MoveClientToWaitingList), ctx, req)
}

// StartDischarge mocks base method.
func (m *MockClientService) StartDischarge(ctx context.Context, clientID string, req *client.StartDischargeRequest) (*client.StartDischargeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDischarge", ctx, clientID, req)
	ret0, _ := ret[0].(*client.StartDischargeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDischarge indicates an expected call of StartDischarge.
func (mr *MockClientServiceMockRecorder) StartDischarge(ctx, clientID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDischarge", reflect.TypeOf((*MockClientService)(nil).StartDischarge), ctx, clientID, req)
}
