// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/lib/token (interfaces: TokenManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_token_manager.go -package=mocks care-cordination/lib/token TokenManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	token "care-cordination/lib/token"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenManager is a mock of TokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
	isgomock struct{}
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockTokenManager) GenerateAccessToken(userID, employeeID string, now time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID, employeeID, now)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenManagerMockRecorder) GenerateAccessToken(userID, employeeID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenManager)(nil).GenerateAccessToken), userID, employeeID, now)
}

// GenerateMFAPendingToken mocks base method.
func (m *MockTokenManager) GenerateMFAPendingToken(userID string, now time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMFAPendingToken", userID, now)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateMFAPendingToken indicates an expected call of GenerateMFAPendingToken.
func (mr *MockTokenManagerMockRecorder) GenerateMFAPendingToken(userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMFAPendingToken", reflect.TypeOf((*MockTokenManager)(nil).GenerateMFAPendingToken), userID, now)
}

// GenerateRefreshToken mocks base method.
func (m *MockTokenManager) GenerateRefreshToken(userID string, now time.Time) (string, *token.RefreshTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID, now)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*token.RefreshTokenClaims)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockTokenManagerMockRecorder) GenerateRefreshToken(userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockTokenManager)(nil).GenerateRefreshToken), userID, now)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenManager) ValidateAccessToken(tokenStr string) (*token.AccessTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenStr)
	ret0, _ := ret[0].(*token.AccessTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenManagerMockRecorder) ValidateAccessToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenManager)(nil).ValidateAccessToken), tokenStr)
}

// ValidateRefreshToken mocks base method.
func (m *MockTokenManager) ValidateRefreshToken(tokenStr string) (*token.RefreshTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", tokenStr)
	ret0, _ := ret[0].(*token.RefreshTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockTokenManagerMockRecorder) ValidateRefreshToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockTokenManager)(nil).ValidateRefreshToken), tokenStr)
}
