// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (
    id,
    filekey,
    content_type
) VALUES (
    $1, $2, $3
)
`

type CreateAttachmentParams struct {
	ID          string `json:"id"`
	Filekey     string `json:"filekey"`
	ContentType string `json:"content_type"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment, arg.ID, arg.Filekey, arg.ContentType)
	return err
}
