// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_goals.sql

package db

import (
	"context"
)

const createClientGoal = `-- name: CreateClientGoal :exec
INSERT INTO client_goals (
    id,
    intake_form_id,
    client_id,
    title,
    description
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateClientGoalParams struct {
	ID           string  `json:"id"`
	IntakeFormID string  `json:"intake_form_id"`
	ClientID     *string `json:"client_id"`
	Title        string  `json:"title"`
	Description  *string `json:"description"`
}

func (q *Queries) CreateClientGoal(ctx context.Context, arg CreateClientGoalParams) error {
	_, err := q.db.Exec(ctx, createClientGoal,
		arg.ID,
		arg.IntakeFormID,
		arg.ClientID,
		arg.Title,
		arg.Description,
	)
	return err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM client_goals WHERE id = $1
`

func (q *Queries) DeleteGoal(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGoal, id)
	return err
}

const linkGoalsToClient = `-- name: LinkGoalsToClient :exec
UPDATE client_goals 
SET client_id = $1, updated_at = NOW() 
WHERE intake_form_id = $2 AND client_id IS NULL
`

type LinkGoalsToClientParams struct {
	ClientID     *string `json:"client_id"`
	IntakeFormID string  `json:"intake_form_id"`
}

func (q *Queries) LinkGoalsToClient(ctx context.Context, arg LinkGoalsToClientParams) error {
	_, err := q.db.Exec(ctx, linkGoalsToClient, arg.ClientID, arg.IntakeFormID)
	return err
}

const listGoalsByClientID = `-- name: ListGoalsByClientID :many
SELECT id, intake_form_id, client_id, title, description, created_at, updated_at FROM client_goals WHERE client_id = $1
`

func (q *Queries) ListGoalsByClientID(ctx context.Context, clientID *string) ([]ClientGoal, error) {
	rows, err := q.db.Query(ctx, listGoalsByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientGoal{}
	for rows.Next() {
		var i ClientGoal
		if err := rows.Scan(
			&i.ID,
			&i.IntakeFormID,
			&i.ClientID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByIntakeID = `-- name: ListGoalsByIntakeID :many
SELECT id, intake_form_id, client_id, title, description, created_at, updated_at FROM client_goals WHERE intake_form_id = $1
`

func (q *Queries) ListGoalsByIntakeID(ctx context.Context, intakeFormID string) ([]ClientGoal, error) {
	rows, err := q.db.Query(ctx, listGoalsByIntakeID, intakeFormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientGoal{}
	for rows.Next() {
		var i ClientGoal
		if err := rows.Scan(
			&i.ID,
			&i.IntakeFormID,
			&i.ClientID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientGoal = `-- name: UpdateClientGoal :exec
UPDATE client_goals SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
`

type UpdateClientGoalParams struct {
	ID          string  `json:"id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateClientGoal(ctx context.Context, arg UpdateClientGoalParams) error {
	_, err := q.db.Exec(ctx, updateClientGoal, arg.ID, arg.Title, arg.Description)
	return err
}
