// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :exec
INSERT INTO employees (
    id,
    user_id,
    first_name,
    last_name,
    bsn,
    date_of_birth,
    phone_number,
    gender,
    role
) VALUES (
 $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateEmployeeParams struct {
	ID          string      `json:"id"`
	UserID      string      `json:"user_id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Bsn         string      `json:"bsn"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	PhoneNumber string      `json:"phone_number"`
	Gender      GenderEnum  `json:"gender"`
	Role        string      `json:"role"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error {
	_, err := q.db.Exec(ctx, createEmployee,
		arg.ID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Bsn,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.Gender,
		arg.Role,
	)
	return err
}

const listEmployees = `-- name: ListEmployees :many
SELECT
    e.id,
    e.user_id,
    e.first_name,
    e.last_name,
    e.bsn,
    e.date_of_birth,
    e.phone_number,
    e.gender,
    e.role,
    COUNT(*) OVER() as total_count
FROM employees e
WHERE
(
  $3::text IS NULL OR
  e.first_name ILIKE '%' || $3::text || '%' OR
  e.last_name ILIKE '%' || $3::text || '%' OR
  CONCAT(e.first_name, ' ', e.last_name) ILIKE '%' || $3::text || '%'
)
ORDER BY e.first_name, e.last_name
LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

type ListEmployeesRow struct {
	ID          string      `json:"id"`
	UserID      string      `json:"user_id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Bsn         string      `json:"bsn"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	PhoneNumber string      `json:"phone_number"`
	Gender      GenderEnum  `json:"gender"`
	Role        string      `json:"role"`
	TotalCount  int64       `json:"total_count"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Bsn,
			&i.DateOfBirth,
			&i.PhoneNumber,
			&i.Gender,
			&i.Role,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
