// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CareTypeEnum string

const (
	CareTypeEnumProtectedLiving           CareTypeEnum = "protected_living"
	CareTypeEnumSemiIndependentLiving     CareTypeEnum = "semi_independent_living"
	CareTypeEnumIndependentAssistedLiving CareTypeEnum = "independent_assisted_living"
	CareTypeEnumAmbulatoryCare            CareTypeEnum = "ambulatory_care"
)

func (e *CareTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CareTypeEnum(s)
	case string:
		*e = CareTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CareTypeEnum: %T", src)
	}
	return nil
}

type NullCareTypeEnum struct {
	CareTypeEnum CareTypeEnum `json:"care_type_enum"`
	Valid        bool         `json:"valid"` // Valid is true if CareTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCareTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CareTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CareTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCareTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CareTypeEnum), nil
}

type ClientStatusEnum string

const (
	ClientStatusEnumWaitingList ClientStatusEnum = "waiting_list"
	ClientStatusEnumInCare      ClientStatusEnum = "in_care"
	ClientStatusEnumDischarged  ClientStatusEnum = "discharged"
)

func (e *ClientStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientStatusEnum(s)
	case string:
		*e = ClientStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientStatusEnum: %T", src)
	}
	return nil
}

type NullClientStatusEnum struct {
	ClientStatusEnum ClientStatusEnum `json:"client_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ClientStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ClientStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientStatusEnum), nil
}

type GenderEnum string

const (
	GenderEnumMale   GenderEnum = "male"
	GenderEnumFemale GenderEnum = "female"
	GenderEnumOther  GenderEnum = "other"
)

func (e *GenderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderEnum(s)
	case string:
		*e = GenderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderEnum: %T", src)
	}
	return nil
}

type NullGenderEnum struct {
	GenderEnum GenderEnum `json:"gender_enum"`
	Valid      bool       `json:"valid"` // Valid is true if GenderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GenderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderEnum), nil
}

type IntakeStatusEnum string

const (
	IntakeStatusEnumCompleted IntakeStatusEnum = "completed"
	IntakeStatusEnumPending   IntakeStatusEnum = "pending"
)

func (e *IntakeStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntakeStatusEnum(s)
	case string:
		*e = IntakeStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for IntakeStatusEnum: %T", src)
	}
	return nil
}

type NullIntakeStatusEnum struct {
	IntakeStatusEnum IntakeStatusEnum `json:"intake_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if IntakeStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntakeStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.IntakeStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntakeStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntakeStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntakeStatusEnum), nil
}

type RegistrationStatusEnum string

const (
	RegistrationStatusEnumPending  RegistrationStatusEnum = "pending"
	RegistrationStatusEnumApproved RegistrationStatusEnum = "approved"
	RegistrationStatusEnumRejected RegistrationStatusEnum = "rejected"
	RegistrationStatusEnumInReview RegistrationStatusEnum = "in_review"
)

func (e *RegistrationStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegistrationStatusEnum(s)
	case string:
		*e = RegistrationStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RegistrationStatusEnum: %T", src)
	}
	return nil
}

type NullRegistrationStatusEnum struct {
	RegistrationStatusEnum RegistrationStatusEnum `json:"registration_status_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if RegistrationStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegistrationStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RegistrationStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegistrationStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegistrationStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegistrationStatusEnum), nil
}

type WaitingListPriorityEnum string

const (
	WaitingListPriorityEnumLow    WaitingListPriorityEnum = "low"
	WaitingListPriorityEnumNormal WaitingListPriorityEnum = "normal"
	WaitingListPriorityEnumHigh   WaitingListPriorityEnum = "high"
)

func (e *WaitingListPriorityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaitingListPriorityEnum(s)
	case string:
		*e = WaitingListPriorityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for WaitingListPriorityEnum: %T", src)
	}
	return nil
}

type NullWaitingListPriorityEnum struct {
	WaitingListPriorityEnum WaitingListPriorityEnum `json:"waiting_list_priority_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if WaitingListPriorityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaitingListPriorityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.WaitingListPriorityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaitingListPriorityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaitingListPriorityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaitingListPriorityEnum), nil
}

type Attachment struct {
	ID          string             `json:"id"`
	Filekey     string             `json:"filekey"`
	ContentType string             `json:"content_type"`
	UploadedAt  pgtype.Timestamptz `json:"uploaded_at"`
}

type Client struct {
	ID                  string                  `json:"id"`
	FirstName           string                  `json:"first_name"`
	LastName            string                  `json:"last_name"`
	Bsn                 string                  `json:"bsn"`
	DateOfBirth         pgtype.Date             `json:"date_of_birth"`
	PhoneNumber         *string                 `json:"phone_number"`
	Gender              GenderEnum              `json:"gender"`
	RegistrationFormID  string                  `json:"registration_form_id"`
	IntakeFormID        string                  `json:"intake_form_id"`
	CareType            CareTypeEnum            `json:"care_type"`
	ReferringOrgID      *string                 `json:"referring_org_id"`
	Status              ClientStatusEnum        `json:"status"`
	WaitingListPriority WaitingListPriorityEnum `json:"waiting_list_priority"`
	AssignedLocationID  *string                 `json:"assigned_location_id"`
	CoordinatorID       *string                 `json:"coordinator_id"`
	FamilySituation     *string                 `json:"family_situation"`
	Limitations         *string                 `json:"limitations"`
	FocusAreas          *string                 `json:"focus_areas"`
	Goals               *string                 `json:"goals"`
	Notes               *string                 `json:"notes"`
	CreatedAt           pgtype.Timestamp        `json:"created_at"`
	UpdatedAt           pgtype.Timestamp        `json:"updated_at"`
}

type Employee struct {
	ID          string           `json:"id"`
	UserID      string           `json:"user_id"`
	FirstName   string           `json:"first_name"`
	LastName    string           `json:"last_name"`
	Bsn         string           `json:"bsn"`
	DateOfBirth pgtype.Date      `json:"date_of_birth"`
	PhoneNumber string           `json:"phone_number"`
	Gender      GenderEnum       `json:"gender"`
	Role        string           `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type IntakeForm struct {
	ID                 string           `json:"id"`
	RegistrationFormID string           `json:"registration_form_id"`
	IntakeDate         pgtype.Date      `json:"intake_date"`
	IntakeTime         pgtype.Time      `json:"intake_time"`
	LocationID         string           `json:"location_id"`
	CoordinatorID      string           `json:"coordinator_id"`
	FamilySituation    *string          `json:"family_situation"`
	MainProvider       *string          `json:"main_provider"`
	Limitations        *string          `json:"limitations"`
	FocusAreas         *string          `json:"focus_areas"`
	Goals              *string          `json:"goals"`
	Notes              *string          `json:"notes"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type Location struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	PostalCode string             `json:"postal_code"`
	Address    string             `json:"address"`
	Capacity   int32              `json:"capacity"`
	Occupied   int32              `json:"occupied"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ReferringOrg struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	ContactPerson string             `json:"contact_person"`
	PhoneNumber   string             `json:"phone_number"`
	Email         string             `json:"email"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RegistrationForm struct {
	ID                 string                     `json:"id"`
	FirstName          string                     `json:"first_name"`
	LastName           string                     `json:"last_name"`
	Bsn                string                     `json:"bsn"`
	DateOfBirth        pgtype.Date                `json:"date_of_birth"`
	Gender             GenderEnum                 `json:"gender"`
	RefferingOrgID     *string                    `json:"reffering_org_id"`
	CareType           CareTypeEnum               `json:"care_type"`
	RegistrationDate   pgtype.Timestamp           `json:"registration_date"`
	RegistrationReason string                     `json:"registration_reason"`
	AdditionalNotes    *string                    `json:"additional_notes"`
	Status             NullRegistrationStatusEnum `json:"status"`
	AttachmentIds      []string                   `json:"attachment_ids"`
	CreatedAt          pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz         `json:"updated_at"`
}

type Session struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	TokenFamily string             `json:"token_family"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UserAgent   *string            `json:"user_agent"`
	IpAddress   *string            `json:"ip_address"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
