// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id,
    user_id,
    type,
    priority,
    title,
    message,
    resource_type,
    resource_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, type, priority, title, message, resource_type, resource_id, is_read, read_at, created_at, expires_at
`

type CreateNotificationParams struct {
	ID           string                   `json:"id"`
	UserID       string                   `json:"user_id"`
	Type         NotificationTypeEnum     `json:"type"`
	Priority     NotificationPriorityEnum `json:"priority"`
	Title        string                   `json:"title"`
	Message      string                   `json:"message"`
	ResourceType *string                  `json:"resource_type"`
	ResourceID   *string                  `json:"resource_id"`
	ExpiresAt    pgtype.Timestamptz       `json:"expires_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Priority,
		arg.Title,
		arg.Message,
		arg.ResourceType,
		arg.ResourceID,
		arg.ExpiresAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Message,
		&i.ResourceType,
		&i.ResourceID,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredNotifications = `-- name: DeleteExpiredNotifications :exec
DELETE FROM notifications
WHERE expires_at IS NOT NULL AND expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNotifications)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, type, priority, title, message, resource_type, resource_id, is_read, read_at, created_at, expires_at FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Message,
		&i.ResourceType,
		&i.ResourceID,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT 
    id, user_id, type, priority, title, message, resource_type, resource_id, is_read, read_at, created_at, expires_at,
    COUNT(*) OVER() as total_count
FROM notifications
WHERE user_id = $1
    AND ($4::boolean IS NULL OR is_read = $4::boolean)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	IsRead *bool  `json:"is_read"`
}

type ListNotificationsRow struct {
	ID           string                   `json:"id"`
	UserID       string                   `json:"user_id"`
	Type         NotificationTypeEnum     `json:"type"`
	Priority     NotificationPriorityEnum `json:"priority"`
	Title        string                   `json:"title"`
	Message      string                   `json:"message"`
	ResourceType *string                  `json:"resource_type"`
	ResourceID   *string                  `json:"resource_id"`
	IsRead       *bool                    `json:"is_read"`
	ReadAt       pgtype.Timestamptz       `json:"read_at"`
	CreatedAt    pgtype.Timestamptz       `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz       `json:"expires_at"`
	TotalCount   int64                    `json:"total_count"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.IsRead,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Priority,
			&i.Title,
			&i.Message,
			&i.ResourceType,
			&i.ResourceID,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE, read_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = TRUE, read_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}
