// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddAppointmentParticipant(ctx context.Context, arg AddAppointmentParticipantParams) error
	// ============================================================
	// Role Permissions
	// ============================================================
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	// ============================================================
	// User Roles
	// ============================================================
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	BatchAssignPermissionsToRole(ctx context.Context, arg BatchAssignPermissionsToRoleParams) error
	ConfirmLocationTransfer(ctx context.Context, id string) error
	CountAuditLogs(ctx context.Context) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	// ============================================================
	// Attachments
	// ============================================================
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// ============================================================
	// Clients
	// ============================================================
	CreateClient(ctx context.Context, arg CreateClientParams) (CreateClientRow, error)
	CreateClientEvaluation(ctx context.Context, arg CreateClientEvaluationParams) (ClientEvaluation, error)
	CreateClientGoal(ctx context.Context, arg CreateClientGoalParams) error
	// ============================================================
	// Employees
	// ============================================================
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error
	CreateGoalProgressLog(ctx context.Context, arg CreateGoalProgressLogParams) error
	// ============================================================
	// Incidents
	// ============================================================
	CreateIncident(ctx context.Context, arg CreateIncidentParams) error
	// ============================================================
	// Intake Forms
	// ============================================================
	CreateIntakeForm(ctx context.Context, arg CreateIntakeFormParams) error
	CreateLocation(ctx context.Context, arg CreateLocationParams) error
	// ============================================================
	// Location Transfers
	// ============================================================
	CreateLocationTransfer(ctx context.Context, arg CreateLocationTransferParams) (CreateLocationTransferRow, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ============================================================
	// Permissions
	// ============================================================
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// ============================================================
	// Referring Orgs
	// ============================================================
	CreateReferringOrg(ctx context.Context, arg CreateReferringOrgParams) error
	CreateRegistrationForm(ctx context.Context, arg CreateRegistrationFormParams) error
	CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error)
	// ============================================================
	// Roles
	// ============================================================
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ============================================================
	// Users
	// ============================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error
	DecrementLocationOccupied(ctx context.Context, id string) error
	DeleteAllPermissionsFromRole(ctx context.Context, roleID string) error
	DeleteAppointment(ctx context.Context, id string) error
	DeleteDraftEvaluation(ctx context.Context, id string) error
	DeleteExpiredNotifications(ctx context.Context) error
	DeleteGoal(ctx context.Context, id string) error
	DeleteGoalProgressLogsByEvaluationId(ctx context.Context, evaluationID string) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeletePermission(ctx context.Context, id string) error
	DeleteReferringOrg(ctx context.Context, id string) error
	DeleteReminder(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, id string) error
	DeleteUserSession(ctx context.Context, tokenHash string) error
	GetAppointment(ctx context.Context, id string) (Appointment, error)
	GetAuditLogByID(ctx context.Context, id string) (GetAuditLogByIDRow, error)
	GetAuditLogBySequence(ctx context.Context, sequenceNumber int64) (AuditLog, error)
	GetAuditLogStats(ctx context.Context) (GetAuditLogStatsRow, error)
	GetAuditLogsByResource(ctx context.Context, arg GetAuditLogsByResourceParams) ([]AuditLog, error)
	GetAuditLogsByUser(ctx context.Context, arg GetAuditLogsByUserParams) ([]AuditLog, error)
	// Get audit logs in sequence order for hash chain verification
	GetAuditLogsForVerification(ctx context.Context, arg GetAuditLogsForVerificationParams) ([]GetAuditLogsForVerificationRow, error)
	GetClientByID(ctx context.Context, id string) (Client, error)
	GetClientEvaluationHistory(ctx context.Context, clientID string) ([]GetClientEvaluationHistoryRow, error)
	GetCoordinatorDrafts(ctx context.Context, arg GetCoordinatorDraftsParams) ([]GetCoordinatorDraftsRow, error)
	GetCriticalEvaluations(ctx context.Context, arg GetCriticalEvaluationsParams) ([]GetCriticalEvaluationsRow, error)
	GetDischargeStats(ctx context.Context) (GetDischargeStatsRow, error)
	GetDraftByClientId(ctx context.Context, clientID string) (ClientEvaluation, error)
	GetDraftEvaluation(ctx context.Context, id string) ([]GetDraftEvaluationRow, error)
	GetEmployeeByID(ctx context.Context, id string) (GetEmployeeByIDRow, error)
	GetEmployeeByUserID(ctx context.Context, userID string) (GetEmployeeByUserIDRow, error)
	GetEvaluationById(ctx context.Context, id string) (ClientEvaluation, error)
	GetEvaluationDetails(ctx context.Context, id string) ([]GetEvaluationDetailsRow, error)
	// Get clients with evaluations due in the next 3 days for reminder notifications
	GetEvaluationsDueSoon(ctx context.Context) ([]GetEvaluationsDueSoonRow, error)
	GetInCareStats(ctx context.Context) (GetInCareStatsRow, error)
	GetIncident(ctx context.Context, id string) (GetIncidentRow, error)
	GetIncidentStats(ctx context.Context) (GetIncidentStatsRow, error)
	GetIntakeForm(ctx context.Context, id string) (IntakeForm, error)
	GetIntakeFormWithDetails(ctx context.Context, id string) (GetIntakeFormWithDetailsRow, error)
	GetIntakeStats(ctx context.Context) (GetIntakeStatsRow, error)
	GetLastClientEvaluation(ctx context.Context, clientID string) ([]GetLastClientEvaluationRow, error)
	// Get the most recent audit log entry to retrieve its hash for the chain
	GetLatestAuditLog(ctx context.Context) (GetLatestAuditLogRow, error)
	GetLocationCapacityStats(ctx context.Context) (GetLocationCapacityStatsRow, error)
	GetLocationTransferByID(ctx context.Context, id string) (GetLocationTransferByIDRow, error)
	GetLocationTransferStats(ctx context.Context) (GetLocationTransferStatsRow, error)
	GetNotification(ctx context.Context, id string) (Notification, error)
	// Get reminders due in the next hour that haven't been completed
	GetPendingRemindersByDueTime(ctx context.Context) ([]Reminder, error)
	GetPermissionByID(ctx context.Context, id string) (Permission, error)
	GetRecentEvaluationsGlobal(ctx context.Context, arg GetRecentEvaluationsGlobalParams) ([]GetRecentEvaluationsGlobalRow, error)
	GetReferringOrgByID(ctx context.Context, id string) (ReferringOrg, error)
	GetReferringOrgStats(ctx context.Context) (GetReferringOrgStatsRow, error)
	GetRegistrationForm(ctx context.Context, id string) (RegistrationForm, error)
	GetRegistrationFormWithDetails(ctx context.Context, id string) (GetRegistrationFormWithDetailsRow, error)
	GetRegistrationStats(ctx context.Context) (GetRegistrationStatsRow, error)
	GetReminder(ctx context.Context, id string) (Reminder, error)
	GetRoleByID(ctx context.Context, id string) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRoleForUser(ctx context.Context, userID string) (Role, error)
	GetScheduledEvaluations(ctx context.Context, arg GetScheduledEvaluationsParams) ([]GetScheduledEvaluationsRow, error)
	GetUnreadCount(ctx context.Context, userID string) (int64, error)
	// Get appointments starting in the next hour for reminder notifications
	GetUpcomingAppointments(ctx context.Context) ([]GetUpcomingAppointmentsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserIDsByRoleName(ctx context.Context, name string) ([]string, error)
	GetUserSession(ctx context.Context, tokenHash string) (Session, error)
	GetWaitlistStats(ctx context.Context) (GetWaitlistStatsRow, error)
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
	IncrementLocationOccupied(ctx context.Context, id string) error
	LinkGoalsToClient(ctx context.Context, arg LinkGoalsToClientParams) error
	ListAppointmentParticipants(ctx context.Context, appointmentID string) ([]AppointmentParticipant, error)
	ListAppointmentsByOrganizer(ctx context.Context, organizerID string) ([]Appointment, error)
	ListAppointmentsByParticipant(ctx context.Context, arg ListAppointmentsByParticipantParams) ([]Appointment, error)
	ListAppointmentsByRange(ctx context.Context, arg ListAppointmentsByRangeParams) ([]Appointment, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListDischargedClients(ctx context.Context, arg ListDischargedClientsParams) ([]ListDischargedClientsRow, error)
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error)
	ListGoalsByClientID(ctx context.Context, clientID *string) ([]ClientGoal, error)
	ListGoalsByIntakeID(ctx context.Context, intakeFormID string) ([]ClientGoal, error)
	ListInCareClients(ctx context.Context, arg ListInCareClientsParams) ([]ListInCareClientsRow, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error)
	ListIntakeForms(ctx context.Context, arg ListIntakeFormsParams) ([]ListIntakeFormsRow, error)
	ListLocationTransfers(ctx context.Context, arg ListLocationTransfersParams) ([]ListLocationTransfersRow, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]ListPermissionsRow, error)
	ListPermissionsForRole(ctx context.Context, roleID string) ([]Permission, error)
	ListRecurringAppointments(ctx context.Context, arg ListRecurringAppointmentsParams) ([]Appointment, error)
	ListReferringOrgs(ctx context.Context, arg ListReferringOrgsParams) ([]ListReferringOrgsRow, error)
	ListReferringOrgsWithCounts(ctx context.Context, arg ListReferringOrgsWithCountsParams) ([]ListReferringOrgsWithCountsRow, error)
	ListRegistrationForms(ctx context.Context, arg ListRegistrationFormsParams) ([]ListRegistrationFormsRow, error)
	ListRemindersByRange(ctx context.Context, arg ListRemindersByRangeParams) ([]Reminder, error)
	ListRemindersByUser(ctx context.Context, userID string) ([]Reminder, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error)
	ListUsersWithRole(ctx context.Context, roleID string) ([]ListUsersWithRoleRow, error)
	ListWaitingListClients(ctx context.Context, arg ListWaitingListClientsParams) ([]ListWaitingListClientsRow, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID string) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	RefuseLocationTransfer(ctx context.Context, arg RefuseLocationTransferParams) error
	RemoveAppointmentParticipants(ctx context.Context, appointmentID string) error
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, userID string) error
	SoftDeleteEmployee(ctx context.Context, id string) error
	SoftDeleteIncident(ctx context.Context, id string) error
	SoftDeleteLocation(ctx context.Context, id string) error
	SoftDeleteRegistrationForm(ctx context.Context, id string) error
	SubmitDraftEvaluation(ctx context.Context, id string) (ClientEvaluation, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (string, error)
	UpdateClientByIntakeFormID(ctx context.Context, arg UpdateClientByIntakeFormIDParams) error
	UpdateClientByRegistrationFormID(ctx context.Context, arg UpdateClientByRegistrationFormIDParams) error
	UpdateClientEvaluation(ctx context.Context, arg UpdateClientEvaluationParams) (ClientEvaluation, error)
	UpdateClientGoal(ctx context.Context, arg UpdateClientGoalParams) error
	UpdateClientNextEvaluationDate(ctx context.Context, arg UpdateClientNextEvaluationDateParams) error
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
	UpdateGoalProgressLog(ctx context.Context, arg UpdateGoalProgressLogParams) error
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) error
	UpdateIntakeForm(ctx context.Context, arg UpdateIntakeFormParams) error
	UpdateIntakeFormStatus(ctx context.Context, arg UpdateIntakeFormStatusParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) error
	UpdateLocationTransfer(ctx context.Context, arg UpdateLocationTransferParams) error
	UpdateReferringOrg(ctx context.Context, arg UpdateReferringOrgParams) error
	UpdateRegistrationForm(ctx context.Context, arg UpdateRegistrationFormParams) error
	UpdateRegistrationFormStatus(ctx context.Context, arg UpdateRegistrationFormStatusParams) error
	UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) error
}

var _ Querier = (*Queries)(nil)
