// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) (CreateClientRow, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error
	CreateIncident(ctx context.Context, arg CreateIncidentParams) error
	CreateIntakeForm(ctx context.Context, arg CreateIntakeFormParams) error
	CreateLocation(ctx context.Context, arg CreateLocationParams) error
	CreateLocationTransfer(ctx context.Context, arg CreateLocationTransferParams) (CreateLocationTransferRow, error)
	CreateReferringOrg(ctx context.Context, arg CreateReferringOrgParams) error
	CreateRegistrationForm(ctx context.Context, arg CreateRegistrationFormParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error
	DeleteReferringOrg(ctx context.Context, id string) error
	DeleteUserSession(ctx context.Context, tokenHash string) error
	GetClientByID(ctx context.Context, id string) (Client, error)
	GetIntakeForm(ctx context.Context, id string) (IntakeForm, error)
	GetReferringOrgByID(ctx context.Context, id string) (ReferringOrg, error)
	GetRegistrationForm(ctx context.Context, id string) (RegistrationForm, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserSession(ctx context.Context, tokenHash string) (Session, error)
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error)
	ListInCareClients(ctx context.Context, arg ListInCareClientsParams) ([]ListInCareClientsRow, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error)
	ListIntakeForms(ctx context.Context, arg ListIntakeFormsParams) ([]ListIntakeFormsRow, error)
	ListLocationTransfers(ctx context.Context, arg ListLocationTransfersParams) ([]ListLocationTransfersRow, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error)
	ListReferringOrgs(ctx context.Context, arg ListReferringOrgsParams) ([]ListReferringOrgsRow, error)
	ListRegistrationForms(ctx context.Context, arg ListRegistrationFormsParams) ([]ListRegistrationFormsRow, error)
	ListWaitingListClients(ctx context.Context, arg ListWaitingListClientsParams) ([]ListWaitingListClientsRow, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (string, error)
	UpdateIntakeFormStatus(ctx context.Context, arg UpdateIntakeFormStatusParams) error
	UpdateReferringOrg(ctx context.Context, arg UpdateReferringOrgParams) error
	UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) error
}

var _ Querier = (*Queries)(nil)
