// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec

INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

// ============================================================
// Role Permissions
// ============================================================
func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec

INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET role_id = $2, assigned_at = CURRENT_TIMESTAMP
`

type AssignRoleToUserParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

// ============================================================
// User Roles
// ============================================================
func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const batchAssignPermissionsToRole = `-- name: BatchAssignPermissionsToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1::text, UNNEST($2::text[])
ON CONFLICT DO NOTHING
`

type BatchAssignPermissionsToRoleParams struct {
	RoleID        string   `json:"role_id"`
	PermissionIds []string `json:"permission_ids"`
}

func (q *Queries) BatchAssignPermissionsToRole(ctx context.Context, arg BatchAssignPermissionsToRoleParams) error {
	_, err := q.db.Exec(ctx, batchAssignPermissionsToRole, arg.RoleID, arg.PermissionIds)
	return err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (id, resource, action, description)
VALUES ($1, $2, $3, $4)
RETURNING id, resource, action, description, created_at
`

type CreatePermissionParams struct {
	ID          string  `json:"id"`
	Resource    string  `json:"resource"`
	Action      string  `json:"action"`
	Description *string `json:"description"`
}

// ============================================================
// Permissions
// ============================================================
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.ID,
		arg.Resource,
		arg.Action,
		arg.Description,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one

INSERT INTO roles (id, name, description)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_at
`

type CreateRoleParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

// ============================================================
// Roles
// ============================================================
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllPermissionsFromRole = `-- name: DeleteAllPermissionsFromRole :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteAllPermissionsFromRole(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteAllPermissionsFromRole, roleID)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, resource, action, description, created_at FROM permissions WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, created_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleForUser = `-- name: GetRoleForUser :one
SELECT r.id, r.name, r.description, r.created_at
FROM roles r
JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetRoleForUser(ctx context.Context, userID string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleForUser, userID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, resource, action, description, created_at, COUNT(*) OVER() as total_count
FROM permissions
ORDER BY resource, action
LIMIT $1 OFFSET $2
`

type ListPermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPermissionsRow struct {
	ID          string             `json:"id"`
	Resource    string             `json:"resource"`
	Action      string             `json:"action"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TotalCount  int64              `json:"total_count"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsRow{}
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT p.id, p.resource, p.action, p.description, p.created_at
FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.resource, p.action
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT 
    r.id, r.name, r.description, r.created_at,
    COUNT(*) OVER() as total_count,
    (SELECT COUNT(*) FROM role_permissions rp WHERE rp.role_id = r.id) as permission_count,
    (SELECT COUNT(*) FROM user_roles ur WHERE ur.role_id = r.id) as user_count
FROM roles r
ORDER BY r.name
LIMIT $1 OFFSET $2
`

type ListRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRolesRow struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TotalCount      int64              `json:"total_count"`
	PermissionCount int64              `json:"permission_count"`
	UserCount       int64              `json:"user_count"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.TotalCount,
			&i.PermissionCount,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT u.id, u.email
FROM users u
JOIN user_roles ur ON u.id = ur.user_id
WHERE ur.role_id = $1
ORDER BY u.email
`

type ListUsersWithRoleRow struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) ListUsersWithRole(ctx context.Context, roleID string) ([]ListUsersWithRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithRoleRow{}
	for rows.Next() {
		var i ListUsersWithRoleRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) RemoveRoleFromUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, userID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3
WHERE id = $1
RETURNING id, name, description, created_at
`

type UpdateRoleParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
