// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationForm = `-- name: CreateRegistrationForm :exec
INSERT INTO registration_forms (
    id,
    first_name,
    last_name,
    bsn,
    date_of_birth,
    org_name,
    org_contact_person,
    org_phone_number,
    org_email,
    care_type,
    coordinator_id,
    registration_date,
    registration_reason,
    additional_notes,
    attachment_ids
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 
    $10, $11, $12, $13, $14, $15
)
`

type CreateRegistrationFormParams struct {
	ID                 string           `json:"id"`
	FirstName          string           `json:"first_name"`
	LastName           string           `json:"last_name"`
	Bsn                string           `json:"bsn"`
	DateOfBirth        pgtype.Date      `json:"date_of_birth"`
	OrgName            string           `json:"org_name"`
	OrgContactPerson   string           `json:"org_contact_person"`
	OrgPhoneNumber     string           `json:"org_phone_number"`
	OrgEmail           string           `json:"org_email"`
	CareType           CareTypeEnum     `json:"care_type"`
	CoordinatorID      string           `json:"coordinator_id"`
	RegistrationDate   pgtype.Timestamp `json:"registration_date"`
	RegistrationReason string           `json:"registration_reason"`
	AdditionalNotes    *string          `json:"additional_notes"`
	AttachmentIds      []string         `json:"attachment_ids"`
}

func (q *Queries) CreateRegistrationForm(ctx context.Context, arg CreateRegistrationFormParams) error {
	_, err := q.db.Exec(ctx, createRegistrationForm,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Bsn,
		arg.DateOfBirth,
		arg.OrgName,
		arg.OrgContactPerson,
		arg.OrgPhoneNumber,
		arg.OrgEmail,
		arg.CareType,
		arg.CoordinatorID,
		arg.RegistrationDate,
		arg.RegistrationReason,
		arg.AdditionalNotes,
		arg.AttachmentIds,
	)
	return err
}

const listRegistrationForms = `-- name: ListRegistrationForms :many
SELECT r.id,
        r.first_name,
        r.last_name,
        r.bsn,
        r.date_of_birth,
        r.org_name,
        r.care_type,
        r.coordinator_id,
        e.first_name AS coordinator_first_name,
        e.last_name AS coordinator_last_name,
        r.registration_date,
        r.registration_reason,
        r.attachment_ids
FROM registration_forms r
JOIN employees e ON r.coordinator_id = e.id
`

type ListRegistrationFormsRow struct {
	ID                   string           `json:"id"`
	FirstName            string           `json:"first_name"`
	LastName             string           `json:"last_name"`
	Bsn                  string           `json:"bsn"`
	DateOfBirth          pgtype.Date      `json:"date_of_birth"`
	OrgName              string           `json:"org_name"`
	CareType             CareTypeEnum     `json:"care_type"`
	CoordinatorID        string           `json:"coordinator_id"`
	CoordinatorFirstName string           `json:"coordinator_first_name"`
	CoordinatorLastName  string           `json:"coordinator_last_name"`
	RegistrationDate     pgtype.Timestamp `json:"registration_date"`
	RegistrationReason   string           `json:"registration_reason"`
	AttachmentIds        []string         `json:"attachment_ids"`
}

func (q *Queries) ListRegistrationForms(ctx context.Context) ([]ListRegistrationFormsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistrationFormsRow{}
	for rows.Next() {
		var i ListRegistrationFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Bsn,
			&i.DateOfBirth,
			&i.OrgName,
			&i.CareType,
			&i.CoordinatorID,
			&i.CoordinatorFirstName,
			&i.CoordinatorLastName,
			&i.RegistrationDate,
			&i.RegistrationReason,
			&i.AttachmentIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
