// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationForm = `-- name: CreateRegistrationForm :exec
INSERT INTO registration_forms (
    id,
    first_name,
    last_name,
    bsn,
    gender,
    date_of_birth,
    phone_number,
    reffering_org_id,
    care_type,
    registration_date,
    registration_reason,
    additional_notes,
    attachment_ids
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13
)
`

type CreateRegistrationFormParams struct {
	ID                 string       `json:"id"`
	FirstName          string       `json:"first_name"`
	LastName           string       `json:"last_name"`
	Bsn                string       `json:"bsn"`
	Gender             GenderEnum   `json:"gender"`
	DateOfBirth        pgtype.Date  `json:"date_of_birth"`
	PhoneNumber        *string      `json:"phone_number"`
	RefferingOrgID     *string      `json:"reffering_org_id"`
	CareType           CareTypeEnum `json:"care_type"`
	RegistrationDate   pgtype.Date  `json:"registration_date"`
	RegistrationReason string       `json:"registration_reason"`
	AdditionalNotes    *string      `json:"additional_notes"`
	AttachmentIds      []string     `json:"attachment_ids"`
}

func (q *Queries) CreateRegistrationForm(ctx context.Context, arg CreateRegistrationFormParams) error {
	_, err := q.db.Exec(ctx, createRegistrationForm,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Bsn,
		arg.Gender,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.RefferingOrgID,
		arg.CareType,
		arg.RegistrationDate,
		arg.RegistrationReason,
		arg.AdditionalNotes,
		arg.AttachmentIds,
	)
	return err
}

const getRegistrationForm = `-- name: GetRegistrationForm :one
SELECT id, first_name, last_name, bsn, date_of_birth, phone_number, gender, reffering_org_id, care_type, registration_date, registration_reason, additional_notes, status, attachment_ids, created_at, updated_at, is_deleted FROM registration_forms WHERE id = $1
`

func (q *Queries) GetRegistrationForm(ctx context.Context, id string) (RegistrationForm, error) {
	row := q.db.QueryRow(ctx, getRegistrationForm, id)
	var i RegistrationForm
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Bsn,
		&i.DateOfBirth,
		&i.PhoneNumber,
		&i.Gender,
		&i.RefferingOrgID,
		&i.CareType,
		&i.RegistrationDate,
		&i.RegistrationReason,
		&i.AdditionalNotes,
		&i.Status,
		&i.AttachmentIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getRegistrationFormWithDetails = `-- name: GetRegistrationFormWithDetails :one
SELECT r.id,
        r.first_name,
        r.last_name,
        r.bsn,
        r.gender,
        r.date_of_birth,
        r.reffering_org_id,
        r.care_type,
        r.registration_date,
        r.registration_reason,
        r.additional_notes,
        r.attachment_ids,
        r.status,
        ro.name as org_name,
        ro.contact_person as org_contact_person,
        ro.phone_number as org_phone_number,
        ro.email as org_email,
        EXISTS (SELECT 1 FROM intake_forms inf WHERE inf.registration_form_id = r.id) AS intake_completed,
        EXISTS (SELECT 1 FROM clients c WHERE c.registration_form_id = r.id) AS has_client
FROM registration_forms r
LEFT JOIN referring_orgs ro ON r.reffering_org_id = ro.id
WHERE r.id = $1
`

type GetRegistrationFormWithDetailsRow struct {
	ID                 string                     `json:"id"`
	FirstName          string                     `json:"first_name"`
	LastName           string                     `json:"last_name"`
	Bsn                string                     `json:"bsn"`
	Gender             GenderEnum                 `json:"gender"`
	DateOfBirth        pgtype.Date                `json:"date_of_birth"`
	RefferingOrgID     *string                    `json:"reffering_org_id"`
	CareType           CareTypeEnum               `json:"care_type"`
	RegistrationDate   pgtype.Date                `json:"registration_date"`
	RegistrationReason string                     `json:"registration_reason"`
	AdditionalNotes    *string                    `json:"additional_notes"`
	AttachmentIds      []string                   `json:"attachment_ids"`
	Status             NullRegistrationStatusEnum `json:"status"`
	OrgName            *string                    `json:"org_name"`
	OrgContactPerson   *string                    `json:"org_contact_person"`
	OrgPhoneNumber     *string                    `json:"org_phone_number"`
	OrgEmail           *string                    `json:"org_email"`
	IntakeCompleted    bool                       `json:"intake_completed"`
	HasClient          bool                       `json:"has_client"`
}

func (q *Queries) GetRegistrationFormWithDetails(ctx context.Context, id string) (GetRegistrationFormWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationFormWithDetails, id)
	var i GetRegistrationFormWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Bsn,
		&i.Gender,
		&i.DateOfBirth,
		&i.RefferingOrgID,
		&i.CareType,
		&i.RegistrationDate,
		&i.RegistrationReason,
		&i.AdditionalNotes,
		&i.AttachmentIds,
		&i.Status,
		&i.OrgName,
		&i.OrgContactPerson,
		&i.OrgPhoneNumber,
		&i.OrgEmail,
		&i.IntakeCompleted,
		&i.HasClient,
	)
	return i, err
}

const getRegistrationStats = `-- name: GetRegistrationStats :one
SELECT 
    COUNT(*) as total_count,
    COUNT(*) FILTER (WHERE status = 'approved') as approved_count,
    COUNT(*) FILTER (WHERE status = 'in_review') as in_review_count
FROM registration_forms
WHERE is_deleted = FALSE
`

type GetRegistrationStatsRow struct {
	TotalCount    int64 `json:"total_count"`
	ApprovedCount int64 `json:"approved_count"`
	InReviewCount int64 `json:"in_review_count"`
}

func (q *Queries) GetRegistrationStats(ctx context.Context) (GetRegistrationStatsRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationStats)
	var i GetRegistrationStatsRow
	err := row.Scan(&i.TotalCount, &i.ApprovedCount, &i.InReviewCount)
	return i, err
}

const listRegistrationForms = `-- name: ListRegistrationForms :many
SELECT r.id,
        r.first_name,
        r.last_name,
        r.bsn,
        r.date_of_birth,
        r.reffering_org_id,
        r.care_type,
        r.registration_date,
        r.registration_reason,
        r.additional_notes,
        r.attachment_ids,
        r.status,
        ro.name as org_name,
        ro.contact_person as org_contact_person,
        ro.phone_number as org_phone_number,
        ro.email as org_email,
        EXISTS (SELECT 1 FROM intake_forms inf WHERE inf.registration_form_id = r.id) AS intake_completed,
        COUNT(r.id) OVER () AS total_count
FROM registration_forms r
LEFT JOIN referring_orgs ro ON r.reffering_org_id = ro.id
WHERE
    (
        -- If search term is NULL or empty, ignore filters
        $3::text IS NULL OR $3::text = '' OR
        -- Search by Org Name
        ro.name ILIKE '%' || $3 || '%' OR
        -- Search by Client First Name
        r.first_name ILIKE '%' || $3 || '%' OR
        -- Search by Client Last Name
        r.last_name ILIKE '%' || $3 || '%'
    )
    AND (
        -- If status is NULL or empty, ignore filter
        $4::text IS NULL OR $4::text = '' OR
        -- Filter by status
        r.status::text = $4::text
    )
    AND (
        -- If intake_completed is NULL, ignore filter
        $5::boolean IS NULL OR
        -- Filter by intake completion status
        EXISTS (SELECT 1 FROM intake_forms inf WHERE inf.registration_form_id = r.id) = $5::boolean
    )
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListRegistrationFormsParams struct {
	Limit           int32   `json:"limit"`
	Offset          int32   `json:"offset"`
	Search          *string `json:"search"`
	Status          *string `json:"status"`
	IntakeCompleted *bool   `json:"intake_completed"`
}

type ListRegistrationFormsRow struct {
	ID                 string                     `json:"id"`
	FirstName          string                     `json:"first_name"`
	LastName           string                     `json:"last_name"`
	Bsn                string                     `json:"bsn"`
	DateOfBirth        pgtype.Date                `json:"date_of_birth"`
	RefferingOrgID     *string                    `json:"reffering_org_id"`
	CareType           CareTypeEnum               `json:"care_type"`
	RegistrationDate   pgtype.Date                `json:"registration_date"`
	RegistrationReason string                     `json:"registration_reason"`
	AdditionalNotes    *string                    `json:"additional_notes"`
	AttachmentIds      []string                   `json:"attachment_ids"`
	Status             NullRegistrationStatusEnum `json:"status"`
	OrgName            *string                    `json:"org_name"`
	OrgContactPerson   *string                    `json:"org_contact_person"`
	OrgPhoneNumber     *string                    `json:"org_phone_number"`
	OrgEmail           *string                    `json:"org_email"`
	IntakeCompleted    bool                       `json:"intake_completed"`
	TotalCount         int64                      `json:"total_count"`
}

func (q *Queries) ListRegistrationForms(ctx context.Context, arg ListRegistrationFormsParams) ([]ListRegistrationFormsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationForms,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Status,
		arg.IntakeCompleted,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistrationFormsRow{}
	for rows.Next() {
		var i ListRegistrationFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Bsn,
			&i.DateOfBirth,
			&i.RefferingOrgID,
			&i.CareType,
			&i.RegistrationDate,
			&i.RegistrationReason,
			&i.AdditionalNotes,
			&i.AttachmentIds,
			&i.Status,
			&i.OrgName,
			&i.OrgContactPerson,
			&i.OrgPhoneNumber,
			&i.OrgEmail,
			&i.IntakeCompleted,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRegistrationForm = `-- name: SoftDeleteRegistrationForm :exec
UPDATE registration_forms SET is_deleted = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteRegistrationForm(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteRegistrationForm, id)
	return err
}

const updateRegistrationForm = `-- name: UpdateRegistrationForm :exec
UPDATE registration_forms SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    bsn = COALESCE($4, bsn),
    gender = COALESCE($5, gender),
    date_of_birth = COALESCE($6, date_of_birth),
    phone_number = COALESCE($7, phone_number),
    reffering_org_id = COALESCE($8, reffering_org_id),
    care_type = COALESCE($9, care_type),
    registration_date = COALESCE($10, registration_date),
    registration_reason = COALESCE($11, registration_reason),
    additional_notes = COALESCE($12, additional_notes),
    status = COALESCE($13, status),
    attachment_ids = COALESCE($14, attachment_ids),
    updated_at = NOW()
WHERE id = $1
`

type UpdateRegistrationFormParams struct {
	ID                 string                     `json:"id"`
	FirstName          *string                    `json:"first_name"`
	LastName           *string                    `json:"last_name"`
	Bsn                *string                    `json:"bsn"`
	Gender             NullGenderEnum             `json:"gender"`
	DateOfBirth        pgtype.Date                `json:"date_of_birth"`
	PhoneNumber        *string                    `json:"phone_number"`
	RefferingOrgID     *string                    `json:"reffering_org_id"`
	CareType           NullCareTypeEnum           `json:"care_type"`
	RegistrationDate   pgtype.Date                `json:"registration_date"`
	RegistrationReason *string                    `json:"registration_reason"`
	AdditionalNotes    *string                    `json:"additional_notes"`
	Status             NullRegistrationStatusEnum `json:"status"`
	AttachmentIds      []string                   `json:"attachment_ids"`
}

func (q *Queries) UpdateRegistrationForm(ctx context.Context, arg UpdateRegistrationFormParams) error {
	_, err := q.db.Exec(ctx, updateRegistrationForm,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Bsn,
		arg.Gender,
		arg.DateOfBirth,
		arg.PhoneNumber,
		arg.RefferingOrgID,
		arg.CareType,
		arg.RegistrationDate,
		arg.RegistrationReason,
		arg.AdditionalNotes,
		arg.Status,
		arg.AttachmentIds,
	)
	return err
}

const updateRegistrationFormStatus = `-- name: UpdateRegistrationFormStatus :exec
UPDATE registration_forms SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateRegistrationFormStatusParams struct {
	ID     string                     `json:"id"`
	Status NullRegistrationStatusEnum `json:"status"`
}

func (q *Queries) UpdateRegistrationFormStatus(ctx context.Context, arg UpdateRegistrationFormStatusParams) error {
	_, err := q.db.Exec(ctx, updateRegistrationFormStatus, arg.ID, arg.Status)
	return err
}
