// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationForm = `-- name: CreateRegistrationForm :exec
INSERT INTO registration_forms (
    id,
    first_name,
    last_name,
    bsn,
    date_of_birth,
    reffering_org_id,
    care_type,
    registration_date,
    registration_reason,
    additional_notes,
    attachment_ids
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
`

type CreateRegistrationFormParams struct {
	ID                 string           `json:"id"`
	FirstName          string           `json:"first_name"`
	LastName           string           `json:"last_name"`
	Bsn                string           `json:"bsn"`
	DateOfBirth        pgtype.Date      `json:"date_of_birth"`
	RefferingOrgID     *string          `json:"reffering_org_id"`
	CareType           CareTypeEnum     `json:"care_type"`
	RegistrationDate   pgtype.Timestamp `json:"registration_date"`
	RegistrationReason string           `json:"registration_reason"`
	AdditionalNotes    *string          `json:"additional_notes"`
	AttachmentIds      []string         `json:"attachment_ids"`
}

func (q *Queries) CreateRegistrationForm(ctx context.Context, arg CreateRegistrationFormParams) error {
	_, err := q.db.Exec(ctx, createRegistrationForm,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Bsn,
		arg.DateOfBirth,
		arg.RefferingOrgID,
		arg.CareType,
		arg.RegistrationDate,
		arg.RegistrationReason,
		arg.AdditionalNotes,
		arg.AttachmentIds,
	)
	return err
}

const listRegistrationForms = `-- name: ListRegistrationForms :many
SELECT r.id,
        r.first_name,
        r.last_name,
        r.bsn,
        r.date_of_birth,
        r.reffering_org_id,
        r.care_type,
        r.registration_date,
        r.registration_reason,
        r.additional_notes,
        r.attachment_ids,
        r.status,
        ro.name as org_name,
        ro.contact_person as org_contact_person,
        ro.phone_number as org_phone_number,
        ro.email as org_email,
        COUNT(r.id) OVER () AS total_count
FROM registration_forms r
LEFT JOIN referring_orgs ro ON r.reffering_org_id = ro.id
WHERE
    (
        -- If search term is NULL or empty, ignore filters
        $3::text IS NULL OR $3::text = '' OR
        -- Search by Org Name
        ro.name ILIKE '%' || $3 || '%' OR
        -- Search by Client First Name
        r.first_name ILIKE '%' || $3 || '%' OR
        -- Search by Client Last Name
        r.last_name ILIKE '%' || $3 || '%'
    )
ORDER BY r.registration_date DESC
LIMIT $1 OFFSET $2
`

type ListRegistrationFormsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

type ListRegistrationFormsRow struct {
	ID                 string                     `json:"id"`
	FirstName          string                     `json:"first_name"`
	LastName           string                     `json:"last_name"`
	Bsn                string                     `json:"bsn"`
	DateOfBirth        pgtype.Date                `json:"date_of_birth"`
	RefferingOrgID     *string                    `json:"reffering_org_id"`
	CareType           CareTypeEnum               `json:"care_type"`
	RegistrationDate   pgtype.Timestamp           `json:"registration_date"`
	RegistrationReason string                     `json:"registration_reason"`
	AdditionalNotes    *string                    `json:"additional_notes"`
	AttachmentIds      []string                   `json:"attachment_ids"`
	Status             NullRegistrationStatusEnum `json:"status"`
	OrgName            *string                    `json:"org_name"`
	OrgContactPerson   *string                    `json:"org_contact_person"`
	OrgPhoneNumber     *string                    `json:"org_phone_number"`
	OrgEmail           *string                    `json:"org_email"`
	TotalCount         int64                      `json:"total_count"`
}

func (q *Queries) ListRegistrationForms(ctx context.Context, arg ListRegistrationFormsParams) ([]ListRegistrationFormsRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationForms, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistrationFormsRow{}
	for rows.Next() {
		var i ListRegistrationFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Bsn,
			&i.DateOfBirth,
			&i.RefferingOrgID,
			&i.CareType,
			&i.RegistrationDate,
			&i.RegistrationReason,
			&i.AdditionalNotes,
			&i.AttachmentIds,
			&i.Status,
			&i.OrgName,
			&i.OrgContactPerson,
			&i.OrgPhoneNumber,
			&i.OrgEmail,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
