// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO sessions (
    id,
    user_id,
    token_hash,
    token_family,
    expires_at,
    user_agent,
    ip_address
) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserSessionParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	TokenHash   string             `json:"token_hash"`
	TokenFamily string             `json:"token_family"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UserAgent   *string            `json:"user_agent"`
	IpAddress   *string            `json:"ip_address"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.Exec(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.TokenFamily,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteUserSession, tokenHash)
	return err
}

const getUserSession = `-- name: GetUserSession :one
SELECT id, user_id, token_family, token_hash, expires_at, user_agent, ip_address, created_at, updated_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetUserSession(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getUserSession, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenFamily,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSession = `-- name: UpdateUserSession :exec
UPDATE sessions SET
    expires_at = $1,
    user_agent = $2,
    ip_address = $3,
    token_family = $4,
    token_hash = $5
WHERE id = $6
`

type UpdateUserSessionParams struct {
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UserAgent   *string            `json:"user_agent"`
	IpAddress   *string            `json:"ip_address"`
	TokenFamily string             `json:"token_family"`
	TokenHash   string             `json:"token_hash"`
	ID          string             `json:"id"`
}

func (q *Queries) UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) error {
	_, err := q.db.Exec(ctx, updateUserSession,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.TokenFamily,
		arg.TokenHash,
		arg.ID,
	)
	return err
}
