// Code generated by MockGen. DO NOT EDIT.
// Source: care-cordination/features/audit (interfaces: AuditService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_audit_service.go -package=mocks care-cordination/features/audit AuditService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	audit "care-cordination/features/audit"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditService is a mock of AuditService interface.
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
	isgomock struct{}
}

// MockAuditServiceMockRecorder is the mock recorder for MockAuditService.
type MockAuditServiceMockRecorder struct {
	mock *MockAuditService
}

// NewMockAuditService creates a new mock instance.
func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	mock := &MockAuditService{ctrl: ctrl}
	mock.recorder = &MockAuditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder {
	return m.recorder
}

// GetAuditLogByID mocks base method.
func (m *MockAuditService) GetAuditLogByID(ctx context.Context, id string) (*audit.AuditLogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLogByID", ctx, id)
	ret0, _ := ret[0].(*audit.AuditLogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLogByID indicates an expected call of GetAuditLogByID.
func (mr *MockAuditServiceMockRecorder) GetAuditLogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLogByID", reflect.TypeOf((*MockAuditService)(nil).GetAuditLogByID), ctx, id)
}

// GetAuditStats mocks base method.
func (m *MockAuditService) GetAuditStats(ctx context.Context) (*audit.AuditLogStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditStats", ctx)
	ret0, _ := ret[0].(*audit.AuditLogStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditStats indicates an expected call of GetAuditStats.
func (mr *MockAuditServiceMockRecorder) GetAuditStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditStats", reflect.TypeOf((*MockAuditService)(nil).GetAuditStats), ctx)
}

// ListAuditLogs mocks base method.
func (m *MockAuditService) ListAuditLogs(ctx context.Context, req *audit.ListAuditLogsRequest, limit, offset int32) ([]audit.AuditLogResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogs", ctx, req, limit, offset)
	ret0, _ := ret[0].([]audit.AuditLogResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAuditLogs indicates an expected call of ListAuditLogs.
func (mr *MockAuditServiceMockRecorder) ListAuditLogs(ctx, req, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogs", reflect.TypeOf((*MockAuditService)(nil).ListAuditLogs), ctx, req, limit, offset)
}

// VerifyChain mocks base method.
func (m *MockAuditService) VerifyChain(ctx context.Context, startSeq, endSeq int64) (*audit.ChainVerificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyChain", ctx, startSeq, endSeq)
	ret0, _ := ret[0].(*audit.ChainVerificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyChain indicates an expected call of VerifyChain.
func (mr *MockAuditServiceMockRecorder) VerifyChain(ctx, startSeq, endSeq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyChain", reflect.TypeOf((*MockAuditService)(nil).VerifyChain), ctx, startSeq, endSeq)
}

// VerifyFullChain mocks base method.
func (m *MockAuditService) VerifyFullChain(ctx context.Context) (*audit.ChainVerificationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyFullChain", ctx)
	ret0, _ := ret[0].(*audit.ChainVerificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyFullChain indicates an expected call of VerifyFullChain.
func (mr *MockAuditServiceMockRecorder) VerifyFullChain(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyFullChain", reflect.TypeOf((*MockAuditService)(nil).VerifyFullChain), ctx)
}
